language: ruby
rvm:
  - 1.8.7
before_script:
  - 'git clone git://github.com/razorsedge/puppet-snmp.git spec/fixtures/modules/snmp'
script: "rake spec"
branches:
  only:
    - master
notifications:
  email:
    - github@razorsedge.org
gemfile: .gemfile
env:
  - PUPPET_VERSION=2.6.4
  - PUPPET_VERSION=2.6.9
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=2.7.12
  - PUPPET_VERSION=2.7.19
